// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gateway/gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	LoginStatus   bool                   `protobuf:"varint,3,opt,name=LoginStatus,proto3" json:"LoginStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetLoginStatus() bool {
	if x != nil {
		return x.LoginStatus
	}
	return false
}

var File_proto_gateway_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/gateway/gateway.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n" +
	"\x05Token\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\tR\x05Value\"_\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04Code\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12 \n" +
	"\vLoginStatus\x18\x03 \x01(\bR\vLoginStatus2\x93\x01\n" +
	"\x13GatewayLoginManager\x12F\n" +
	"\x17CheckGatewayLoginStatus\x12\x16.google.protobuf.Empty\x1a\x11.pb.LoginResponse\"\x00\x124\n" +
	"\x12LoginServerByToken\x12\t.pb.Token\x1a\x11.pb.LoginResponse\"\x00B\x06Z\x04.;pbb\x06proto3"

var (
	file_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_gateway_proto_rawDescData []byte
)

func file_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_gateway_proto_rawDesc), len(file_proto_gateway_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_gateway_proto_rawDescData
}

var file_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gateway_gateway_proto_goTypes = []any{
	(*Token)(nil),         // 0: pb.Token
	(*LoginResponse)(nil), // 1: pb.LoginResponse
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_proto_gateway_gateway_proto_depIdxs = []int32{
	2, // 0: pb.GatewayLoginManager.CheckGatewayLoginStatus:input_type -> google.protobuf.Empty
	0, // 1: pb.GatewayLoginManager.LoginServerByToken:input_type -> pb.Token
	1, // 2: pb.GatewayLoginManager.CheckGatewayLoginStatus:output_type -> pb.LoginResponse
	1, // 3: pb.GatewayLoginManager.LoginServerByToken:output_type -> pb.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_gateway_proto_init() }
func file_proto_gateway_gateway_proto_init() {
	if File_proto_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_gateway_proto_rawDesc), len(file_proto_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_gateway_proto = out.File
	file_proto_gateway_gateway_proto_goTypes = nil
	file_proto_gateway_gateway_proto_depIdxs = nil
}
