// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/mobile/mobile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenIoTHubOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenIoTHubOperationResponse) Reset() {
	*x = OpenIoTHubOperationResponse{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenIoTHubOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIoTHubOperationResponse) ProtoMessage() {}

func (x *OpenIoTHubOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIoTHubOperationResponse.ProtoReflect.Descriptor instead.
func (*OpenIoTHubOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{0}
}

func (x *OpenIoTHubOperationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OpenIoTHubOperationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IoTManagerServerAndToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IoTManagerServerAndToken) Reset() {
	*x = IoTManagerServerAndToken{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoTManagerServerAndToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoTManagerServerAndToken) ProtoMessage() {}

func (x *IoTManagerServerAndToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoTManagerServerAndToken.ProtoReflect.Descriptor instead.
func (*IoTManagerServerAndToken) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{1}
}

func (x *IoTManagerServerAndToken) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *IoTManagerServerAndToken) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *IoTManagerServerAndToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MDNSService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=Instance,proto3" json:"Instance,omitempty"`
	IP            string                 `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	MDNSInfo      string                 `protobuf:"bytes,4,opt,name=MDNSInfo,proto3" json:"MDNSInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSService) Reset() {
	*x = MDNSService{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSService) ProtoMessage() {}

func (x *MDNSService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSService.ProtoReflect.Descriptor instead.
func (*MDNSService) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{2}
}

func (x *MDNSService) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *MDNSService) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *MDNSService) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MDNSService) GetMDNSInfo() string {
	if x != nil {
		return x.MDNSInfo
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=RunId,proto3" json:"RunId,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	Mac           string                 `protobuf:"bytes,4,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{3}
}

func (x *Device) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Device) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Device) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Device) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=Devices,proto3" json:"Devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceList) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

// 几种代理类型
type SessionConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunId             string                 `protobuf:"bytes,1,opt,name=RunId,proto3" json:"RunId,omitempty"`
	Token             string                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	StatusToClient    bool                   `protobuf:"varint,5,opt,name=StatusToClient,proto3" json:"StatusToClient,omitempty"`
	StatusP2PAsClient bool                   `protobuf:"varint,6,opt,name=StatusP2PAsClient,proto3" json:"StatusP2PAsClient,omitempty"`
	StatusP2PAsServer bool                   `protobuf:"varint,7,opt,name=StatusP2PAsServer,proto3" json:"StatusP2PAsServer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{5}
}

func (x *SessionConfig) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SessionConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SessionConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SessionConfig) GetStatusToClient() bool {
	if x != nil {
		return x.StatusToClient
	}
	return false
}

func (x *SessionConfig) GetStatusP2PAsClient() bool {
	if x != nil {
		return x.StatusP2PAsClient
	}
	return false
}

func (x *SessionConfig) GetStatusP2PAsServer() bool {
	if x != nil {
		return x.StatusP2PAsServer
	}
	return false
}

type SessionList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionConfigs []*SessionConfig       `protobuf:"bytes,1,rep,name=SessionConfigs,proto3" json:"SessionConfigs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{6}
}

func (x *SessionList) GetSessionConfigs() []*SessionConfig {
	if x != nil {
		return x.SessionConfigs
	}
	return nil
}

type PortService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// String ip;
	Ip string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	// int port;
	Port int32 `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	// bool isLocal = false;
	IsLocal bool `protobuf:"varint,3,opt,name=IsLocal,proto3" json:"IsLocal,omitempty"`
	// 设备的注册信息
	// Map<String, dynamic> info = Map<String, dynamic>();
	Info          map[string]string `protobuf:"bytes,4,rep,name=Info,proto3" json:"Info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortService) Reset() {
	*x = PortService{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortService) ProtoMessage() {}

func (x *PortService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortService.ProtoReflect.Descriptor instead.
func (*PortService) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{7}
}

func (x *PortService) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PortService) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortService) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *PortService) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

type PortConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Device              *Device                `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
	Uuid                string                 `protobuf:"bytes,2,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	LocalProt           int32                  `protobuf:"varint,5,opt,name=LocalProt,proto3" json:"LocalProt,omitempty"`
	RemotePort          int32                  `protobuf:"varint,6,opt,name=RemotePort,proto3" json:"RemotePort,omitempty"`
	BindAllAddr         bool                   `protobuf:"varint,7,opt,name=BindAllAddr,proto3" json:"BindAllAddr,omitempty"`
	Domain              string                 `protobuf:"bytes,8,opt,name=Domain,proto3" json:"Domain,omitempty"`
	NetworkProtocol     string                 `protobuf:"bytes,9,opt,name=NetworkProtocol,proto3" json:"NetworkProtocol,omitempty"`
	ApplicationProtocol string                 `protobuf:"bytes,10,opt,name=ApplicationProtocol,proto3" json:"ApplicationProtocol,omitempty"`
	RemotePortStatus    bool                   `protobuf:"varint,11,opt,name=RemotePortStatus,proto3" json:"RemotePortStatus,omitempty"`
	MDNSInfo            *PortService           `protobuf:"bytes,12,opt,name=MDNSInfo,proto3" json:"MDNSInfo,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PortConfig) Reset() {
	*x = PortConfig{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortConfig) ProtoMessage() {}

func (x *PortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortConfig.ProtoReflect.Descriptor instead.
func (*PortConfig) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{8}
}

func (x *PortConfig) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *PortConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PortConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PortConfig) GetLocalProt() int32 {
	if x != nil {
		return x.LocalProt
	}
	return 0
}

func (x *PortConfig) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *PortConfig) GetBindAllAddr() bool {
	if x != nil {
		return x.BindAllAddr
	}
	return false
}

func (x *PortConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PortConfig) GetNetworkProtocol() string {
	if x != nil {
		return x.NetworkProtocol
	}
	return ""
}

func (x *PortConfig) GetApplicationProtocol() string {
	if x != nil {
		return x.ApplicationProtocol
	}
	return ""
}

func (x *PortConfig) GetRemotePortStatus() bool {
	if x != nil {
		return x.RemotePortStatus
	}
	return false
}

func (x *PortConfig) GetMDNSInfo() *PortService {
	if x != nil {
		return x.MDNSInfo
	}
	return nil
}

type PortList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortConfigs   []*PortConfig          `protobuf:"bytes,1,rep,name=PortConfigs,proto3" json:"PortConfigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortList) Reset() {
	*x = PortList{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortList) ProtoMessage() {}

func (x *PortList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortList.ProtoReflect.Descriptor instead.
func (*PortList) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{9}
}

func (x *PortList) GetPortConfigs() []*PortConfig {
	if x != nil {
		return x.PortConfigs
	}
	return nil
}

type SOCKS5Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=RunId,proto3" json:"RunId,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	EncType       string                 `protobuf:"bytes,4,opt,name=EncType,proto3" json:"EncType,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SOCKS5Config) Reset() {
	*x = SOCKS5Config{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SOCKS5Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOCKS5Config) ProtoMessage() {}

func (x *SOCKS5Config) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOCKS5Config.ProtoReflect.Descriptor instead.
func (*SOCKS5Config) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{10}
}

func (x *SOCKS5Config) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SOCKS5Config) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SOCKS5Config) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SOCKS5Config) GetEncType() string {
	if x != nil {
		return x.EncType
	}
	return ""
}

func (x *SOCKS5Config) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SOCKS5List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SOCKS5Configs []*SOCKS5Config        `protobuf:"bytes,1,rep,name=SOCKS5Configs,proto3" json:"SOCKS5Configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SOCKS5List) Reset() {
	*x = SOCKS5List{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SOCKS5List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOCKS5List) ProtoMessage() {}

func (x *SOCKS5List) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOCKS5List.ProtoReflect.Descriptor instead.
func (*SOCKS5List) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{11}
}

func (x *SOCKS5List) GetSOCKS5Configs() []*SOCKS5Config {
	if x != nil {
		return x.SOCKS5Configs
	}
	return nil
}

type MDNSServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MDNSServices  []*MDNSService         `protobuf:"bytes,1,rep,name=MDNSServices,proto3" json:"MDNSServices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSServiceList) Reset() {
	*x = MDNSServiceList{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSServiceList) ProtoMessage() {}

func (x *MDNSServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSServiceList.ProtoReflect.Descriptor instead.
func (*MDNSServiceList) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{12}
}

func (x *MDNSServiceList) GetMDNSServices() []*MDNSService {
	if x != nil {
		return x.MDNSServices
	}
	return nil
}

type TokenModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=RunId,proto3" json:"RunId,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	TcpPort       int32                  `protobuf:"varint,3,opt,name=TcpPort,proto3" json:"TcpPort,omitempty"`
	KcpPort       int32                  `protobuf:"varint,4,opt,name=KcpPort,proto3" json:"KcpPort,omitempty"`
	TlsPort       int32                  `protobuf:"varint,5,opt,name=TlsPort,proto3" json:"TlsPort,omitempty"`
	GrpcPort      int32                  `protobuf:"varint,6,opt,name=GrpcPort,proto3" json:"GrpcPort,omitempty"`
	UDPApiPort    int32                  `protobuf:"varint,7,opt,name=UDPApiPort,proto3" json:"UDPApiPort,omitempty"`
	KCPApiPort    int32                  `protobuf:"varint,8,opt,name=KCPApiPort,proto3" json:"KCPApiPort,omitempty"`
	Permission    []string               `protobuf:"bytes,9,rep,name=Permission,proto3" json:"Permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenModel) Reset() {
	*x = TokenModel{}
	mi := &file_proto_mobile_mobile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenModel) ProtoMessage() {}

func (x *TokenModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mobile_mobile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenModel.ProtoReflect.Descriptor instead.
func (*TokenModel) Descriptor() ([]byte, []int) {
	return file_proto_mobile_mobile_proto_rawDescGZIP(), []int{13}
}

func (x *TokenModel) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TokenModel) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TokenModel) GetTcpPort() int32 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

func (x *TokenModel) GetKcpPort() int32 {
	if x != nil {
		return x.KcpPort
	}
	return 0
}

func (x *TokenModel) GetTlsPort() int32 {
	if x != nil {
		return x.TlsPort
	}
	return 0
}

func (x *TokenModel) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *TokenModel) GetUDPApiPort() int32 {
	if x != nil {
		return x.UDPApiPort
	}
	return 0
}

func (x *TokenModel) GetKCPApiPort() int32 {
	if x != nil {
		return x.KCPApiPort
	}
	return 0
}

func (x *TokenModel) GetPermission() []string {
	if x != nil {
		return x.Permission
	}
	return nil
}

var File_proto_mobile_mobile_proto protoreflect.FileDescriptor

const file_proto_mobile_mobile_proto_rawDesc = "" +
	"\n" +
	"\x19proto/mobile/mobile.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"C\n" +
	"\x1bOpenIoTHubOperationResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"X\n" +
	"\x18IoTManagerServerAndToken\x12\x12\n" +
	"\x04Host\x18\x01 \x01(\tR\x04Host\x12\x12\n" +
	"\x04Port\x18\x02 \x01(\x05R\x04Port\x12\x14\n" +
	"\x05Token\x18\x03 \x01(\tR\x05Token\"i\n" +
	"\vMDNSService\x12\x1a\n" +
	"\bInstance\x18\x01 \x01(\tR\bInstance\x12\x0e\n" +
	"\x02IP\x18\x02 \x01(\tR\x02IP\x12\x12\n" +
	"\x04Port\x18\x03 \x01(\x05R\x04Port\x12\x1a\n" +
	"\bMDNSInfo\x18\x04 \x01(\tR\bMDNSInfo\"\x8e\x01\n" +
	"\x06Device\x12\x12\n" +
	"\x04Uuid\x18\x01 \x01(\tR\x04Uuid\x12\x14\n" +
	"\x05RunId\x18\x02 \x01(\tR\x05RunId\x12\x12\n" +
	"\x04Addr\x18\x03 \x01(\tR\x04Addr\x12\x10\n" +
	"\x03Mac\x18\x04 \x01(\tR\x03Mac\x12\x12\n" +
	"\x04Name\x18\x05 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x06 \x01(\tR\vDescription\"2\n" +
	"\n" +
	"DeviceList\x12$\n" +
	"\aDevices\x18\x01 \x03(\v2\n" +
	".pb.DeviceR\aDevices\"\xf5\x01\n" +
	"\rSessionConfig\x12\x14\n" +
	"\x05RunId\x18\x01 \x01(\tR\x05RunId\x12\x14\n" +
	"\x05Token\x18\x02 \x01(\tR\x05Token\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12&\n" +
	"\x0eStatusToClient\x18\x05 \x01(\bR\x0eStatusToClient\x12,\n" +
	"\x11StatusP2PAsClient\x18\x06 \x01(\bR\x11StatusP2PAsClient\x12,\n" +
	"\x11StatusP2PAsServer\x18\a \x01(\bR\x11StatusP2PAsServer\"H\n" +
	"\vSessionList\x129\n" +
	"\x0eSessionConfigs\x18\x01 \x03(\v2\x11.pb.SessionConfigR\x0eSessionConfigs\"\xb3\x01\n" +
	"\vPortService\x12\x0e\n" +
	"\x02Ip\x18\x01 \x01(\tR\x02Ip\x12\x12\n" +
	"\x04Port\x18\x02 \x01(\x05R\x04Port\x12\x18\n" +
	"\aIsLocal\x18\x03 \x01(\bR\aIsLocal\x12-\n" +
	"\x04Info\x18\x04 \x03(\v2\x19.pb.PortService.InfoEntryR\x04Info\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x03\n" +
	"\n" +
	"PortConfig\x12\"\n" +
	"\x06Device\x18\x01 \x01(\v2\n" +
	".pb.DeviceR\x06Device\x12\x12\n" +
	"\x04Uuid\x18\x02 \x01(\tR\x04Uuid\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x1c\n" +
	"\tLocalProt\x18\x05 \x01(\x05R\tLocalProt\x12\x1e\n" +
	"\n" +
	"RemotePort\x18\x06 \x01(\x05R\n" +
	"RemotePort\x12 \n" +
	"\vBindAllAddr\x18\a \x01(\bR\vBindAllAddr\x12\x16\n" +
	"\x06Domain\x18\b \x01(\tR\x06Domain\x12(\n" +
	"\x0fNetworkProtocol\x18\t \x01(\tR\x0fNetworkProtocol\x120\n" +
	"\x13ApplicationProtocol\x18\n" +
	" \x01(\tR\x13ApplicationProtocol\x12*\n" +
	"\x10RemotePortStatus\x18\v \x01(\bR\x10RemotePortStatus\x12+\n" +
	"\bMDNSInfo\x18\f \x01(\v2\x0f.pb.PortServiceR\bMDNSInfo\"<\n" +
	"\bPortList\x120\n" +
	"\vPortConfigs\x18\x01 \x03(\v2\x0e.pb.PortConfigR\vPortConfigs\"\x90\x01\n" +
	"\fSOCKS5Config\x12\x14\n" +
	"\x05RunId\x18\x01 \x01(\tR\x05RunId\x12\x12\n" +
	"\x04Port\x18\x02 \x01(\x05R\x04Port\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\x12\x18\n" +
	"\aEncType\x18\x04 \x01(\tR\aEncType\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\"D\n" +
	"\n" +
	"SOCKS5List\x126\n" +
	"\rSOCKS5Configs\x18\x01 \x03(\v2\x10.pb.SOCKS5ConfigR\rSOCKS5Configs\"F\n" +
	"\x0fMDNSServiceList\x123\n" +
	"\fMDNSServices\x18\x01 \x03(\v2\x0f.pb.MDNSServiceR\fMDNSServices\"\x80\x02\n" +
	"\n" +
	"TokenModel\x12\x14\n" +
	"\x05RunId\x18\x01 \x01(\tR\x05RunId\x12\x12\n" +
	"\x04Host\x18\x02 \x01(\tR\x04Host\x12\x18\n" +
	"\aTcpPort\x18\x03 \x01(\x05R\aTcpPort\x12\x18\n" +
	"\aKcpPort\x18\x04 \x01(\x05R\aKcpPort\x12\x18\n" +
	"\aTlsPort\x18\x05 \x01(\x05R\aTlsPort\x12\x1a\n" +
	"\bGrpcPort\x18\x06 \x01(\x05R\bGrpcPort\x12\x1e\n" +
	"\n" +
	"UDPApiPort\x18\a \x01(\x05R\n" +
	"UDPApiPort\x12\x1e\n" +
	"\n" +
	"KCPApiPort\x18\b \x01(\x05R\n" +
	"KCPApiPort\x12\x1e\n" +
	"\n" +
	"Permission\x18\t \x03(\tR\n" +
	"Permission2\xfe\x05\n" +
	"\x0eSessionManager\x12:\n" +
	"\x10CreateOneSession\x12\x11.pb.SessionConfig\x1a\x11.pb.SessionConfig\"\x00\x12?\n" +
	"\x10DeleteOneSession\x12\x11.pb.SessionConfig\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\rGetOneSession\x12\x11.pb.SessionConfig\x1a\x11.pb.SessionConfig\"\x00\x12:\n" +
	"\rGetAllSession\x12\x16.google.protobuf.Empty\x1a\x0f.pb.SessionList\"\x00\x12F\n" +
	"\x1cUpdateSessionNameDescription\x12\x11.pb.SessionConfig\x1a\x11.pb.SessionConfig\"\x00\x127\n" +
	"\x0fCreateOneSOCKS5\x12\x10.pb.SOCKS5Config\x1a\x10.pb.SOCKS5Config\"\x00\x12=\n" +
	"\x0fDeleteOneSOCKS5\x12\x10.pb.SOCKS5Config\x1a\x16.google.protobuf.Empty\"\x00\x124\n" +
	"\fGetOneSOCKS5\x12\x10.pb.SOCKS5Config\x1a\x10.pb.SOCKS5Config\"\x00\x12C\n" +
	"\x14RefreshmDNSProxyList\x12\x11.pb.SessionConfig\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\x12CreateTcpProxyList\x12\f.pb.PortList\x1a\x16.google.protobuf.Empty\"\x00\x12.\n" +
	"\tGetAllTCP\x12\x11.pb.SessionConfig\x1a\f.pb.PortList\"\x00\x12Q\n" +
	"\x19DeleteRemoteGatewayConfig\x12\x11.pb.SessionConfig\x1a\x1f.pb.OpenIoTHubOperationResponse\"\x002\xea\x06\n" +
	"\x13CommonDeviceManager\x121\n" +
	"\tAddDevice\x12\n" +
	".pb.Device\x1a\x16.google.protobuf.Empty\"\x00\x121\n" +
	"\tDelDevice\x12\n" +
	".pb.Device\x1a\x16.google.protobuf.Empty\"\x00\x128\n" +
	"\fGetAllDevice\x12\x16.google.protobuf.Empty\x1a\x0e.pb.DeviceList\"\x00\x124\n" +
	"\fSetDeviceMac\x12\n" +
	".pb.Device\x1a\x16.google.protobuf.Empty\"\x00\x121\n" +
	"\tWakeOnLAN\x12\n" +
	".pb.Device\x1a\x16.google.protobuf.Empty\"\x00\x120\n" +
	"\fCreateOneTCP\x12\x0e.pb.PortConfig\x1a\x0e.pb.PortConfig\"\x00\x128\n" +
	"\fDeleteOneTCP\x12\x0e.pb.PortConfig\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\tGetOneTCP\x12\x0e.pb.PortConfig\x1a\x0e.pb.PortConfig\"\x00\x12'\n" +
	"\tGetAllTCP\x12\n" +
	".pb.Device\x1a\f.pb.PortList\"\x00\x120\n" +
	"\fCreateOneUDP\x12\x0e.pb.PortConfig\x1a\x0e.pb.PortConfig\"\x00\x128\n" +
	"\fDeleteOneUDP\x12\x0e.pb.PortConfig\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\tGetOneUDP\x12\x0e.pb.PortConfig\x1a\x0e.pb.PortConfig\"\x00\x12'\n" +
	"\tGetAllUDP\x12\n" +
	".pb.Device\x1a\f.pb.PortList\"\x00\x120\n" +
	"\fCreateOneFTP\x12\x0e.pb.PortConfig\x1a\x0e.pb.PortConfig\"\x00\x128\n" +
	"\fDeleteOneFTP\x12\x0e.pb.PortConfig\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\tGetOneFTP\x12\x0e.pb.PortConfig\x1a\x0e.pb.PortConfig\"\x00\x12'\n" +
	"\tGetAllFTP\x12\n" +
	".pb.Device\x1a\f.pb.PortList\"\x002\xb6\x05\n" +
	"\x05Utils\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12V\n" +
	"\x13SyncConfigWithToken\x12\x1c.pb.IoTManagerServerAndToken\x1a\x1f.pb.OpenIoTHubOperationResponse\"\x00\x12[\n" +
	"\x18SyncConfigWithJsonConfig\x12\x1c.google.protobuf.StringValue\x1a\x1f.pb.OpenIoTHubOperationResponse\"\x00\x12F\n" +
	"\fGetAllConfig\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValue\"\x00\x12G\n" +
	"\rLoadAllConfig\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\x15GetAllmDNSServiceList\x12\x16.google.protobuf.Empty\x1a\x13.pb.MDNSServiceList\"\x00\x12O\n" +
	"\x18GetmDNSServiceListByType\x12\x1c.google.protobuf.StringValue\x1a\x13.pb.MDNSServiceList\"\x00\x12S\n" +
	"\x13ConvertOctonaryUtf8\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\"\x00\x12?\n" +
	"\rGetTokenModel\x12\x1c.google.protobuf.StringValue\x1a\x0e.pb.TokenModel\"\x00B\x06Z\x04.;pbb\x06proto3"

var (
	file_proto_mobile_mobile_proto_rawDescOnce sync.Once
	file_proto_mobile_mobile_proto_rawDescData []byte
)

func file_proto_mobile_mobile_proto_rawDescGZIP() []byte {
	file_proto_mobile_mobile_proto_rawDescOnce.Do(func() {
		file_proto_mobile_mobile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mobile_mobile_proto_rawDesc), len(file_proto_mobile_mobile_proto_rawDesc)))
	})
	return file_proto_mobile_mobile_proto_rawDescData
}

var file_proto_mobile_mobile_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_mobile_mobile_proto_goTypes = []any{
	(*OpenIoTHubOperationResponse)(nil), // 0: pb.OpenIoTHubOperationResponse
	(*IoTManagerServerAndToken)(nil),    // 1: pb.IoTManagerServerAndToken
	(*MDNSService)(nil),                 // 2: pb.MDNSService
	(*Device)(nil),                      // 3: pb.Device
	(*DeviceList)(nil),                  // 4: pb.DeviceList
	(*SessionConfig)(nil),               // 5: pb.SessionConfig
	(*SessionList)(nil),                 // 6: pb.SessionList
	(*PortService)(nil),                 // 7: pb.PortService
	(*PortConfig)(nil),                  // 8: pb.PortConfig
	(*PortList)(nil),                    // 9: pb.PortList
	(*SOCKS5Config)(nil),                // 10: pb.SOCKS5Config
	(*SOCKS5List)(nil),                  // 11: pb.SOCKS5List
	(*MDNSServiceList)(nil),             // 12: pb.MDNSServiceList
	(*TokenModel)(nil),                  // 13: pb.TokenModel
	nil,                                 // 14: pb.PortService.InfoEntry
	(*emptypb.Empty)(nil),               // 15: google.protobuf.Empty
	(*wrapperspb.StringValue)(nil),      // 16: google.protobuf.StringValue
}
var file_proto_mobile_mobile_proto_depIdxs = []int32{
	3,  // 0: pb.DeviceList.Devices:type_name -> pb.Device
	5,  // 1: pb.SessionList.SessionConfigs:type_name -> pb.SessionConfig
	14, // 2: pb.PortService.Info:type_name -> pb.PortService.InfoEntry
	3,  // 3: pb.PortConfig.Device:type_name -> pb.Device
	7,  // 4: pb.PortConfig.MDNSInfo:type_name -> pb.PortService
	8,  // 5: pb.PortList.PortConfigs:type_name -> pb.PortConfig
	10, // 6: pb.SOCKS5List.SOCKS5Configs:type_name -> pb.SOCKS5Config
	2,  // 7: pb.MDNSServiceList.MDNSServices:type_name -> pb.MDNSService
	5,  // 8: pb.SessionManager.CreateOneSession:input_type -> pb.SessionConfig
	5,  // 9: pb.SessionManager.DeleteOneSession:input_type -> pb.SessionConfig
	5,  // 10: pb.SessionManager.GetOneSession:input_type -> pb.SessionConfig
	15, // 11: pb.SessionManager.GetAllSession:input_type -> google.protobuf.Empty
	5,  // 12: pb.SessionManager.UpdateSessionNameDescription:input_type -> pb.SessionConfig
	10, // 13: pb.SessionManager.CreateOneSOCKS5:input_type -> pb.SOCKS5Config
	10, // 14: pb.SessionManager.DeleteOneSOCKS5:input_type -> pb.SOCKS5Config
	10, // 15: pb.SessionManager.GetOneSOCKS5:input_type -> pb.SOCKS5Config
	5,  // 16: pb.SessionManager.RefreshmDNSProxyList:input_type -> pb.SessionConfig
	9,  // 17: pb.SessionManager.CreateTcpProxyList:input_type -> pb.PortList
	5,  // 18: pb.SessionManager.GetAllTCP:input_type -> pb.SessionConfig
	5,  // 19: pb.SessionManager.DeleteRemoteGatewayConfig:input_type -> pb.SessionConfig
	3,  // 20: pb.CommonDeviceManager.AddDevice:input_type -> pb.Device
	3,  // 21: pb.CommonDeviceManager.DelDevice:input_type -> pb.Device
	15, // 22: pb.CommonDeviceManager.GetAllDevice:input_type -> google.protobuf.Empty
	3,  // 23: pb.CommonDeviceManager.SetDeviceMac:input_type -> pb.Device
	3,  // 24: pb.CommonDeviceManager.WakeOnLAN:input_type -> pb.Device
	8,  // 25: pb.CommonDeviceManager.CreateOneTCP:input_type -> pb.PortConfig
	8,  // 26: pb.CommonDeviceManager.DeleteOneTCP:input_type -> pb.PortConfig
	8,  // 27: pb.CommonDeviceManager.GetOneTCP:input_type -> pb.PortConfig
	3,  // 28: pb.CommonDeviceManager.GetAllTCP:input_type -> pb.Device
	8,  // 29: pb.CommonDeviceManager.CreateOneUDP:input_type -> pb.PortConfig
	8,  // 30: pb.CommonDeviceManager.DeleteOneUDP:input_type -> pb.PortConfig
	8,  // 31: pb.CommonDeviceManager.GetOneUDP:input_type -> pb.PortConfig
	3,  // 32: pb.CommonDeviceManager.GetAllUDP:input_type -> pb.Device
	8,  // 33: pb.CommonDeviceManager.CreateOneFTP:input_type -> pb.PortConfig
	8,  // 34: pb.CommonDeviceManager.DeleteOneFTP:input_type -> pb.PortConfig
	8,  // 35: pb.CommonDeviceManager.GetOneFTP:input_type -> pb.PortConfig
	3,  // 36: pb.CommonDeviceManager.GetAllFTP:input_type -> pb.Device
	15, // 37: pb.Utils.Ping:input_type -> google.protobuf.Empty
	1,  // 38: pb.Utils.SyncConfigWithToken:input_type -> pb.IoTManagerServerAndToken
	16, // 39: pb.Utils.SyncConfigWithJsonConfig:input_type -> google.protobuf.StringValue
	15, // 40: pb.Utils.GetAllConfig:input_type -> google.protobuf.Empty
	16, // 41: pb.Utils.LoadAllConfig:input_type -> google.protobuf.StringValue
	15, // 42: pb.Utils.GetAllmDNSServiceList:input_type -> google.protobuf.Empty
	16, // 43: pb.Utils.GetmDNSServiceListByType:input_type -> google.protobuf.StringValue
	16, // 44: pb.Utils.ConvertOctonaryUtf8:input_type -> google.protobuf.StringValue
	16, // 45: pb.Utils.GetTokenModel:input_type -> google.protobuf.StringValue
	5,  // 46: pb.SessionManager.CreateOneSession:output_type -> pb.SessionConfig
	15, // 47: pb.SessionManager.DeleteOneSession:output_type -> google.protobuf.Empty
	5,  // 48: pb.SessionManager.GetOneSession:output_type -> pb.SessionConfig
	6,  // 49: pb.SessionManager.GetAllSession:output_type -> pb.SessionList
	5,  // 50: pb.SessionManager.UpdateSessionNameDescription:output_type -> pb.SessionConfig
	10, // 51: pb.SessionManager.CreateOneSOCKS5:output_type -> pb.SOCKS5Config
	15, // 52: pb.SessionManager.DeleteOneSOCKS5:output_type -> google.protobuf.Empty
	10, // 53: pb.SessionManager.GetOneSOCKS5:output_type -> pb.SOCKS5Config
	15, // 54: pb.SessionManager.RefreshmDNSProxyList:output_type -> google.protobuf.Empty
	15, // 55: pb.SessionManager.CreateTcpProxyList:output_type -> google.protobuf.Empty
	9,  // 56: pb.SessionManager.GetAllTCP:output_type -> pb.PortList
	0,  // 57: pb.SessionManager.DeleteRemoteGatewayConfig:output_type -> pb.OpenIoTHubOperationResponse
	15, // 58: pb.CommonDeviceManager.AddDevice:output_type -> google.protobuf.Empty
	15, // 59: pb.CommonDeviceManager.DelDevice:output_type -> google.protobuf.Empty
	4,  // 60: pb.CommonDeviceManager.GetAllDevice:output_type -> pb.DeviceList
	15, // 61: pb.CommonDeviceManager.SetDeviceMac:output_type -> google.protobuf.Empty
	15, // 62: pb.CommonDeviceManager.WakeOnLAN:output_type -> google.protobuf.Empty
	8,  // 63: pb.CommonDeviceManager.CreateOneTCP:output_type -> pb.PortConfig
	15, // 64: pb.CommonDeviceManager.DeleteOneTCP:output_type -> google.protobuf.Empty
	8,  // 65: pb.CommonDeviceManager.GetOneTCP:output_type -> pb.PortConfig
	9,  // 66: pb.CommonDeviceManager.GetAllTCP:output_type -> pb.PortList
	8,  // 67: pb.CommonDeviceManager.CreateOneUDP:output_type -> pb.PortConfig
	15, // 68: pb.CommonDeviceManager.DeleteOneUDP:output_type -> google.protobuf.Empty
	8,  // 69: pb.CommonDeviceManager.GetOneUDP:output_type -> pb.PortConfig
	9,  // 70: pb.CommonDeviceManager.GetAllUDP:output_type -> pb.PortList
	8,  // 71: pb.CommonDeviceManager.CreateOneFTP:output_type -> pb.PortConfig
	15, // 72: pb.CommonDeviceManager.DeleteOneFTP:output_type -> google.protobuf.Empty
	8,  // 73: pb.CommonDeviceManager.GetOneFTP:output_type -> pb.PortConfig
	9,  // 74: pb.CommonDeviceManager.GetAllFTP:output_type -> pb.PortList
	15, // 75: pb.Utils.Ping:output_type -> google.protobuf.Empty
	0,  // 76: pb.Utils.SyncConfigWithToken:output_type -> pb.OpenIoTHubOperationResponse
	0,  // 77: pb.Utils.SyncConfigWithJsonConfig:output_type -> pb.OpenIoTHubOperationResponse
	16, // 78: pb.Utils.GetAllConfig:output_type -> google.protobuf.StringValue
	15, // 79: pb.Utils.LoadAllConfig:output_type -> google.protobuf.Empty
	12, // 80: pb.Utils.GetAllmDNSServiceList:output_type -> pb.MDNSServiceList
	12, // 81: pb.Utils.GetmDNSServiceListByType:output_type -> pb.MDNSServiceList
	16, // 82: pb.Utils.ConvertOctonaryUtf8:output_type -> google.protobuf.StringValue
	13, // 83: pb.Utils.GetTokenModel:output_type -> pb.TokenModel
	46, // [46:84] is the sub-list for method output_type
	8,  // [8:46] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_mobile_mobile_proto_init() }
func file_proto_mobile_mobile_proto_init() {
	if File_proto_mobile_mobile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mobile_mobile_proto_rawDesc), len(file_proto_mobile_mobile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_mobile_mobile_proto_goTypes,
		DependencyIndexes: file_proto_mobile_mobile_proto_depIdxs,
		MessageInfos:      file_proto_mobile_mobile_proto_msgTypes,
	}.Build()
	File_proto_mobile_mobile_proto = out.File
	file_proto_mobile_mobile_proto_goTypes = nil
	file_proto_mobile_mobile_proto_depIdxs = nil
}
